### PR TITLE
Annie branch

### PR DESCRIPTION
**Pull request by anniemahlberg**
Annie (and pair programmers Sammy and Niko) 

1. Set up api initial routes users, products, carts and imported them into api/index.js
2. Set up buildTables() function in db/init_db.js
3. Set up models/user models/product and models/cart and imported/exported them in models/index.js

### CODE REVIEW

**Comment by sester2** [comment]
This the review that we made as the navigators for the db init

**Review by Nikoboykin — APPROVED** [review]
Looks good

**Review by sester2 — APPROVED** [review]
This is the table set up that we made together for the db init.

**Review by sester2 — APPROVED** [review]
Leaving the approval for the db

**Pull request merged**
